version: "3"

services:
  parser:
    build: ./parser
    expose:
      - "8000"
    volumes:
      - ./parser:/go/src/parser
      - ./api:/go/src/api
    deploy:
      resources:
        limits:
          memory: 200M
    depends_on:
      - centre

  centre:
    build: ./centre
    expose:
      - "8080"
    volumes:
      - ./centre:/go/src/centre
      - ./api:/go/src/api
    depends_on:
      - db_centre

  db_centre:
    image: postgres
    expose:
    - "5432"