version: "3"

services:
  parser:
    build: ./parser
    expose:
      - "8000"
    volumes:
      - .:/go/src/parser
    deploy:
      resources:
        limits:
          memory: 200M

  centre:
    build: ./centre
    expose:
      - "8080"
    volumes:
      - .:/go/src/centre
    depends_on:
      - db_centre


  db_centre:
    image: postgres
    expose:
    - "5432"